services:
  django:
    build: .
    volumes:
      - ./:/app
    ports:
      - 8000:8000

    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15.4-alpine
    environment:
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password
      - POSTGRES_DB=django_db
    ports:
      - "5432:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U django_user -d django_db" ]
      interval: 5s
      timeout: 3s
      retries: 2