# Generated by Django 5.0.7 on 2024-10-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catbreed',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название породы'),
        ),
    ]
