# Generated by Django 5.0.7 on 2024-10-02 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.catbreed', verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='catbreed',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название породы'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Bad'), (2, 'Average'), (3, 'Good'), (4, 'Verygood'), (5, 'Excellent')], default=3, verbose_name='Оценка'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'cat')},
        ),
    ]
