# Generated by Django 5.0.7 on 2024-10-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_alter_catbreed_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='breed',
            field=models.CharField(max_length=150, unique=True, verbose_name='Порода'),
        ),
    ]
